[[pages]]
path = "main.py"
name = "Find Instruments"
icon = "ğŸ”"

[[pages]]
path = "app/pages/1_AI_Assistance.py"
name = "AI Assistance"
icon = "ğŸ¤–"

[[pages]]
path = "app/pages/2_Submit.py"
name = "Submit Results"
icon = "ğŸ“¤"
